WITH 
margin_balance_hist AS (
	SELECT
		C_ACCOUNT_CODE,
		C_TRADING_DATE AS C_DATE,
		MONTH(C_TRADING_DATE) AS C_MONTH,
    	YEAR(C_TRADING_DATE)  AS C_YEAR,
    	SUM(C_INTERM_LOAN - C_INTERM_LOAN_OUT + C_OUTTERM_LOAN - C_OUTTERM_LOAN_OUT) AS C_MARGIN_DEBT
    FROM  {{ref('fact_t_margin_extra_balance_his')}}
    GROUP BY C_ACCOUNT_CODE, C_TRADING_DATE
),
tlo_balance_hist AS (
	SELECT 
		C_ACCOUNT_CODE,
		C_TRANSACTION_DATE AS C_DATE,
		MONTH(C_TRANSACTION_DATE) AS C_MONTH,
    	YEAR(C_TRANSACTION_DATE)  AS C_YEAR,
		SUM(C_INTERM_BALANCE - C_INTERM_CASH_OUT + C_OUTTERM_BALANCE - C_OUTTERM_CASH_OUT + C_MBS_EXPIRE_DEBIT - C_TLO_COL_1) AS C_MBLINK_DEBT
	FROM  {{ref('fact_t_tlo_debit_balance_history')}}
	GROUP BY C_ACCOUNT_CODE, C_TRANSACTION_DATE
),
back_adv_withdraw AS (
	SELECT 
		C_ACCOUNT_CODE,
		C_WITHDRAW_DATE AS C_DATE,
		MONTH(C_WITHDRAW_DATE) AS C_MONTH,
    	YEAR(C_WITHDRAW_DATE)  AS C_YEAR,
		SUM(C_CASH_VOLUME) AS C_UTTB
	FROM  {{ref('fact_t_back_advance_withdraw')}}
	GROUP BY C_ACCOUNT_CODE, C_WITHDRAW_DATE
),
back_deal_history AS (
	SELECT
		C_ACCOUNT_CODE,
		C_TRANSACTION_DATE AS C_DATE,
		MONTH(C_TRANSACTION_DATE) AS C_MONTH,
    	YEAR(C_TRANSACTION_DATE)  AS C_YEAR,
    	SUM(C_MATCHED_PRICE * C_MATCHED_VOLUME) AS C_GTGD
    FROM  {{ref('fact_t_back_deal_history')}}
    GROUP BY C_ACCOUNT_CODE, C_TRANSACTION_DATE
),
OUTER_TABLE as (
SELECT
	COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE, d.C_ACCOUNT_CODE) AS C_ACCOUNT_CODE,
	COALESCE(m.C_DATE, t.C_DATE, b.C_DATE, d.C_DATE) AS C_DATE,
	COALESCE(m.C_MONTH, t.C_MONTH, b.C_MONTH, d.C_MONTH) AS C_MONTH,
	COALESCE(m.C_YEAR, t.C_YEAR, b.C_YEAR, d.C_YEAR) AS C_YEAR,
	COALESCE(m.C_MARGIN_DEBT,0) AS C_MARGIN_DEBT,
	COALESCE(t.C_MBLINK_DEBT,0) AS C_MBLINK_DEBT,
	COALESCE(b.C_UTTB,0) AS C_UTTB,
	COALESCE(d.C_GTGD,0) AS C_GTGD,
	CONCAT(
		LEFT(COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE, d.C_ACCOUNT_CODE),6),
		'_',
		COALESCE(m.C_YEAR, t.C_YEAR, b.C_YEAR, d.C_YEAR),
		'_',
		COALESCE(m.C_MONTH, t.C_MONTH, b.C_MONTH, d.C_MONTH)) AS C_RANKING_KEY
FROM margin_balance_hist m
FULL OUTER JOIN tlo_balance_hist t
	ON m.C_ACCOUNT_CODE = t.C_ACCOUNT_CODE AND m.C_DATE = t.C_DATE
FULL OUTER JOIN back_adv_withdraw b
	ON COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE) = b.C_ACCOUNT_CODE 
   AND COALESCE(m.C_DATE, t.C_DATE) = b.C_DATE
FULL OUTER JOIN back_deal_history d
	ON COALESCE(m.C_ACCOUNT_CODE, t.C_ACCOUNT_CODE, b.C_ACCOUNT_CODE) = d.C_ACCOUNT_CODE
   AND COALESCE(m.C_DATE, t.C_DATE, b.C_DATE) = d.C_DATE
   )
 SELECT ot.*
 FROM OUTER_TABLE ot
JOIN (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY C_ACCOUNT_CODE ORDER BY updated_at DESC) AS rn
    FROM {{ref('t_back_account')}}
) b 
  ON ot.C_ACCOUNT_CODE = b.C_ACCOUNT_CODE
 WHERE b.rn = 1