SELECT 
	left(C_ACCOUNT_CODE,6) as C_ORIGIN_ACCOUNT_CODE,
	C_ACCOUNT_CODE,
	C_OPEN_DATE,
	CASE 
        	WHEN C_ACCOUNT_BRANCH_CODE = '17' THEN 'KDS'
        	ELSE 'SSG'
    	END AS C_BRANCH_NAME,
	CASE 
        	WHEN C_CHANNEL = 'MBB' THEN 'MB'
        	ELSE 'MBS'
    	END AS C_CHANNEL_NAME
FROM (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY C_ACCOUNT_CODE ORDER BY updated_at DESC) AS rn
    FROM {{ref('t_back_account')}}
) sub
WHERE rn = 1
AND C_ACCOUNT_CODE IS NOT NULL